// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	ID        string
	Title     string
	Completed pgtype.Bool
}

type User struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	ID        string
	Username  string
	Email     string
}
