// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, id string) error
	GetAllTodos(ctx context.Context) ([]Todo, error)
	GetTodoByID(ctx context.Context, id string) (Todo, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
