-- Schema snapshot consumed by sqlc to generate type-safe Go.
-- This file is regenerated by `dbmate dump` after running migrations; keep it
-- in sync via `make migrate` rather than editing by hand.

CREATE TABLE IF NOT EXISTS users (
  id         TEXT PRIMARY KEY,
  username   TEXT NOT NULL UNIQUE,
  email      TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- dbmate bookkeeping table (created automatically by dbmate).
CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY
);
